using Octokit;

namespace Ticket2PR.Api.Services;

public class GitHubService
{
    private readonly ILogger<GitHubService> _logger;
    private readonly string _githubToken;

    public GitHubService(ILogger<GitHubService> logger, IConfiguration configuration)
    {
        _logger = logger;
        _githubToken = configuration["GitHub:Token"] ?? throw new InvalidOperationException("GitHub token not configured");
    }

    public async Task<string> CreatePullRequest(string repoUrl, string branchName, string ticketDescription)
    {
        _logger.LogInformation("Creating pull request for branch {BranchName}", branchName);
        
        var (owner, repoName) = ParseGitHubUrl(repoUrl);
        
        var client = new GitHubClient(new ProductHeaderValue("Ticket2PR"))
        {
            Credentials = new Credentials(_githubToken)
        };

        var pullRequest = new NewPullRequest(
            $"Implement: {ticketDescription.Substring(0, Math.Min(50, ticketDescription.Length))}",
            branchName,
            "main")
        {
            Body = $"This PR implements the following ticket:\n\n{ticketDescription}\n\nAutomatically generated by Ticket2PR."
        };

        var createdPr = await client.PullRequest.Create(owner, repoName, pullRequest);
        
        _logger.LogInformation("Pull request created: {PrUrl}", createdPr.HtmlUrl);
        return createdPr.HtmlUrl;
    }

    public (string owner, string repo) ParseGitHubUrl(string url)
    {
        // Handle various GitHub URL formats
        // https://github.com/owner/repo
        // https://github.com/owner/repo.git
        // git@github.com:owner/repo.git
        
        var cleaned = url.Replace(".git", "")
                        .Replace("git@github.com:", "https://github.com/");
        
        var uri = new Uri(cleaned);
        var parts = uri.AbsolutePath.Trim('/').Split('/');
        
        if (parts.Length < 2)
        {
            throw new ArgumentException($"Invalid GitHub URL: {url}");
        }
        
        return (parts[0], parts[1]);
    }

    public string GetGitHubToken()
    {
        return _githubToken;
    }
}
